/* Generated by cbindgen — do not edit */

/*
 * Thread safety
 * -------------
 * Vault handles (void* returned by vault_open / vault_create) are NOT
 * thread-safe.  All calls on the same handle must be serialized by the
 * caller.  Passing the same handle to multiple threads concurrently is
 * undefined behaviour.
 *
 * Atomic saves
 * ------------
 * vault_save_to() truncates and overwrites the file directly.  It is
 * intentionally non-atomic — the caller MUST write to a temporary file
 * then rename over the target path to guarantee crash safety.
 */

#ifndef CITADEL_CORE_H
#define CITADEL_CORE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes returned across the FFI boundary.
 */
typedef enum VaultResult {
    VAULT_RESULT_OK = 0,
    VAULT_RESULT_WRONG_PASSWORD = 1,
    VAULT_RESULT_FILE_CORRUPTED = 2,
    VAULT_RESULT_FILE_NOT_FOUND = 3,
    VAULT_RESULT_WRITE_FAILED = 4,
    VAULT_RESULT_VALIDATION_FAILED = 5,
    VAULT_RESULT_EMPTY_PASSWORD = 6,
    VAULT_RESULT_INTERNAL_ERROR = 99,
} VaultResult;

/**
 * Entry summary for list operations — never contains passwords.
 */
typedef struct CEntryListItem {
    char *uuid;
    char *title;
    char *username;
    char *url;
} CEntryListItem;

/**
 * Owned list of entry summaries, allocated by Rust, freed by `entry_list_free`.
 */
typedef struct CEntryList {
    struct CEntryListItem *entries;
    uint32_t count;
} CEntryList;

/**
 * Full entry data including password as a byte buffer (not a C string).
 * The password field points to `password_len` bytes of data. It is NOT
 * null-terminated. Allocated by Rust, freed by `entry_data_free`.
 */
typedef struct CEntryData {
    char *uuid;
    char *title;
    char *username;
    uint8_t *password;
    uint32_t password_len;
    char *url;
    char *notes;
} CEntryData;

/**
 * Bitmask flags for password character sets.
 */
typedef struct CharsetFlags {

} CharsetFlags;
#define CharsetFlags_LOWERCASE 1
#define CharsetFlags_UPPERCASE 2
#define CharsetFlags_DIGITS 4
#define CharsetFlags_SYMBOLS 8

enum VaultResult vault_open(const char *path,
                            const uint8_t *password_ptr,
                            uint32_t password_len,
                            const char *keyfile_path,
                            void **handle_out);

enum VaultResult vault_create(const uint8_t *password_ptr,
                              uint32_t password_len,
                              const char *keyfile_path,
                              void **handle_out);

enum VaultResult vault_save_to(void *handle, const char *path);

enum VaultResult vault_validate(const char *path,
                                const uint8_t *password_ptr,
                                uint32_t password_len,
                                const char *keyfile_path);

void vault_close(void *handle);

enum VaultResult vault_change_password(void *handle,
                                       const uint8_t *new_password_ptr,
                                       uint32_t new_password_len,
                                       const char *new_keyfile_path);

enum VaultResult vault_list_entries(void *handle, struct CEntryList **list_out);

enum VaultResult vault_get_entry(void *handle, const char *uuid_str, struct CEntryData **entry_out);

enum VaultResult vault_add_entry(void *handle,
                                 const char *title,
                                 const char *username,
                                 const uint8_t *password_ptr,
                                 uint32_t password_len,
                                 const char *url,
                                 const char *notes,
                                 char **uuid_out);

enum VaultResult vault_update_entry(void *handle,
                                    const char *uuid_str,
                                    const char *title,
                                    const char *username,
                                    const uint8_t *password_ptr,
                                    uint32_t password_len,
                                    const char *url,
                                    const char *notes);

enum VaultResult vault_delete_entry(void *handle, const char *uuid_str);

/**
 * Generate a random password of `length` bytes into `buf_out`.
 *
 * The buffer receives exactly `length` bytes of password data.  If
 * `buf_len > length`, a null terminator is written at `buf_out[length]`
 * so the buffer can be used as a C string.  Callers that need a C string
 * should allocate `length + 1` bytes.
 */
enum VaultResult generate_password(uint32_t length,
                                   uint32_t charset,
                                   uint8_t *buf_out,
                                   uint32_t buf_len);

/**
 * Free a C string that was allocated by the Rust core (e.g. UUID from vault_add_entry).
 * Callers MUST use this instead of their language's native free to avoid cross-allocator UB.
 */
void string_free(char *ptr);

void entry_list_free(struct CEntryList *list);

void entry_data_free(struct CEntryData *data);

#endif  /* CITADEL_CORE_H */
