/* Generated by cbindgen — do not edit */

/*
 * Thread safety
 * -------------
 * Vault handles (void* returned by vault_open / vault_create) are NOT
 * thread-safe.  All calls on the same handle must be serialized by the
 * caller.  Passing the same handle to multiple threads concurrently is
 * undefined behaviour.
 *
 * Atomic saves
 * ------------
 * vault_save_to() truncates and overwrites the file directly.  It is
 * intentionally non-atomic — the caller MUST write to a temporary file
 * then rename over the target path to guarantee crash safety.
 */

#ifndef CITADEL_CORE_H
#define CITADEL_CORE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes returned across the FFI boundary.
 */
typedef enum VaultResult {
    VAULT_RESULT_OK = 0,
    VAULT_RESULT_WRONG_PASSWORD = 1,
    VAULT_RESULT_FILE_CORRUPTED = 2,
    VAULT_RESULT_FILE_NOT_FOUND = 3,
    VAULT_RESULT_WRITE_FAILED = 4,
    VAULT_RESULT_VALIDATION_FAILED = 5,
    VAULT_RESULT_EMPTY_PASSWORD = 6,
    VAULT_RESULT_INTERNAL_ERROR = 99,
} VaultResult;

/**
 * Entry summary for list operations — never contains passwords.
 */
typedef struct CEntryListItem {
    char *uuid;
    char *title;
    char *username;
    char *url;
    char *group;
    char *entry_type;
    /**
     * Comma-separated tags. Null or empty if no tags.
     */
    char *tags;
    /**
     * Unix timestamp of expiry. 0 means no expiry set.
     */
    int64_t expiry_time;
    /**
     * Unix timestamp of last modification. 0 if unknown.
     */
    int64_t last_modified;
    bool is_favorite;
    /**
     * Number of file attachments on this entry.
     */
    uint32_t attachment_count;
} CEntryListItem;

/**
 * Owned list of entry summaries, allocated by Rust, freed by `entry_list_free`.
 */
typedef struct CEntryList {
    struct CEntryListItem *entries;
    uint32_t count;
} CEntryList;

/**
 * A single custom field on an entry.
 */
typedef struct CCustomField {
    char *key;
    char *value;
    bool is_protected;
} CCustomField;

/**
 * Full entry data including password as a byte buffer (not a C string).
 * The password field points to `password_len` bytes of data. It is NOT
 * null-terminated. Allocated by Rust, freed by `entry_data_free`.
 */
typedef struct CEntryData {
    char *uuid;
    char *title;
    char *username;
    uint8_t *password;
    uint32_t password_len;
    char *url;
    char *notes;
    char *otp_uri;
    char *entry_type;
    struct CCustomField *custom_fields;
    uint32_t custom_field_count;
    /**
     * Unix timestamp of expiry. 0 means no expiry set.
     */
    int64_t expiry_time;
    /**
     * Unix timestamp of last modification. 0 if unknown.
     */
    int64_t last_modified;
    bool is_favorite;
} CEntryData;

/**
 * A single password history item.
 */
typedef struct CHistoryItem {
    char *password;
    /**
     * Unix timestamp of when this password was set.
     */
    int64_t timestamp;
} CHistoryItem;

/**
 * List of password history items, allocated by Rust, freed by `history_list_free`.
 */
typedef struct CHistoryList {
    struct CHistoryItem *items;
    uint32_t count;
} CHistoryList;

/**
 * A single attachment info item (name + size).
 */
typedef struct CAttachmentInfo {
    char *name;
    uint64_t size;
} CAttachmentInfo;

/**
 * List of attachment info items, allocated by Rust, freed by `attachment_list_free`.
 */
typedef struct CAttachmentList {
    struct CAttachmentInfo *items;
    uint32_t count;
} CAttachmentList;

/**
 * Raw attachment data, allocated by Rust, freed by `attachment_data_free`.
 */
typedef struct CAttachmentData {
    uint8_t *data;
    uint64_t len;
} CAttachmentData;

/**
 * Bitmask flags for password character sets.
 */
typedef struct CharsetFlags {

} CharsetFlags;
#define CharsetFlags_LOWERCASE 1
#define CharsetFlags_UPPERCASE 2
#define CharsetFlags_DIGITS 4
#define CharsetFlags_SYMBOLS 8

enum VaultResult vault_open(const char *path,
                            const uint8_t *password_ptr,
                            uint32_t password_len,
                            const char *keyfile_path,
                            void **handle_out);

enum VaultResult vault_create(const uint8_t *password_ptr,
                              uint32_t password_len,
                              const char *keyfile_path,
                              void **handle_out);

/**
 * Create a vault with custom KDF parameters.
 * kdf_memory is in bytes, kdf_iterations is the iteration count, kdf_parallelism is thread count.
 */
enum VaultResult vault_create_with_kdf(const uint8_t *password_ptr,
                                       uint32_t password_len,
                                       const char *keyfile_path,
                                       uint64_t kdf_memory,
                                       uint64_t kdf_iterations,
                                       uint32_t kdf_parallelism,
                                       void **handle_out);

/**
 * Update the KDF parameters on an open vault. Takes effect on next save.
 */
enum VaultResult vault_set_kdf_params(void *handle,
                                      uint64_t kdf_memory,
                                      uint64_t kdf_iterations,
                                      uint32_t kdf_parallelism);

/**
 * Get the outer cipher of an open vault.
 * Returns 0 = ChaCha20, 1 = AES-256, 2 = Twofish.
 * On error (null handle), returns 255.
 */
uint32_t vault_get_cipher(void *handle);

/**
 * Set the outer cipher on an open vault. Takes effect on next save.
 * cipher: 0 = ChaCha20, 1 = AES-256, 2 = Twofish.
 */
enum VaultResult vault_set_cipher(void *handle, uint32_t cipher);

enum VaultResult vault_save_to(void *handle, const char *path);

enum VaultResult vault_validate(const char *path,
                                const uint8_t *password_ptr,
                                uint32_t password_len,
                                const char *keyfile_path);

void vault_close(void *handle);

enum VaultResult vault_change_password(void *handle,
                                       const uint8_t *new_password_ptr,
                                       uint32_t new_password_len,
                                       const char *new_keyfile_path);

enum VaultResult vault_list_entries(void *handle, struct CEntryList **list_out);

enum VaultResult vault_get_entry(void *handle, const char *uuid_str, struct CEntryData **entry_out);

enum VaultResult vault_add_entry(void *handle,
                                 const char *title,
                                 const char *username,
                                 const uint8_t *password_ptr,
                                 uint32_t password_len,
                                 const char *url,
                                 const char *notes,
                                 const char *otp_uri,
                                 const char *group,
                                 int64_t expiry_time,
                                 char **uuid_out);

enum VaultResult vault_update_entry(void *handle,
                                    const char *uuid_str,
                                    const char *title,
                                    const char *username,
                                    const uint8_t *password_ptr,
                                    uint32_t password_len,
                                    const char *url,
                                    const char *notes,
                                    const char *otp_uri,
                                    int64_t expiry_time);

enum VaultResult vault_delete_entry(void *handle, const char *uuid_str);

/**
 * List all group paths in the vault. Returns a null-terminated array of C strings.
 * Free with `group_list_free`.
 */
enum VaultResult vault_list_groups(void *handle, char ***groups_out, uint32_t *count_out);

/**
 * Create a group by slash-separated path. No-op if it already exists.
 */
enum VaultResult vault_create_group(void *handle, const char *path);

/**
 * Free a group list returned by `vault_list_groups`.
 */
void group_list_free(char **groups, uint32_t count);

/**
 * Permanently remove all entries in the Recycle Bin. Returns the number of
 * entries removed via `count_out` (set to 0 if no Recycle Bin exists).
 */
enum VaultResult vault_empty_recyclebin(void *handle, uint32_t *count_out);

/**
 * List entries in the Recycle Bin. Returns the same CEntryList structure.
 * Free with `entry_list_free`.
 */
enum VaultResult vault_list_recycled_entries(void *handle, struct CEntryList **list_out);

/**
 * Restore an entry from the Recycle Bin back to the root group.
 */
enum VaultResult vault_restore_entry(void *handle, const char *uuid_str);

/**
 * Permanently delete a single entry from the Recycle Bin.
 */
enum VaultResult vault_permanently_delete_entry(void *handle, const char *uuid_str);

/**
 * Get the password history for an entry. Returns a list of (password, timestamp) pairs.
 * Free with `history_list_free`.
 */
enum VaultResult vault_get_entry_history(void *handle,
                                         const char *uuid_str,
                                         struct CHistoryList **list_out);

/**
 * Free a history list returned by `vault_get_entry_history`.
 */
void history_list_free(struct CHistoryList *list);

/**
 * List attachments on an entry. Returns a list of (name, size) pairs.
 * Free with `attachment_list_free`.
 */
enum VaultResult vault_list_attachments(void *handle,
                                        const char *uuid_str,
                                        struct CAttachmentList **list_out);

/**
 * Get an attachment's raw data by name.
 * Free with `attachment_data_free`.
 */
enum VaultResult vault_get_attachment(void *handle,
                                      const char *uuid_str,
                                      const char *name,
                                      struct CAttachmentData **data_out);

/**
 * Add an attachment to an entry.
 */
enum VaultResult vault_add_attachment(void *handle,
                                      const char *uuid_str,
                                      const char *name,
                                      const uint8_t *data,
                                      uint64_t data_len);

/**
 * Remove an attachment from an entry by name.
 */
enum VaultResult vault_remove_attachment(void *handle, const char *uuid_str, const char *name);

/**
 * Free an attachment list returned by `vault_list_attachments`.
 */
void attachment_list_free(struct CAttachmentList *list);

/**
 * Free attachment data returned by `vault_get_attachment`.
 */
void attachment_data_free(struct CAttachmentData *data);

enum VaultResult vault_set_favorite(void *handle, const char *uuid_str, bool favorite);

enum VaultResult vault_set_custom_field(void *handle,
                                        const char *uuid_str,
                                        const char *key,
                                        const char *value,
                                        bool is_protected);

enum VaultResult vault_remove_custom_field(void *handle, const char *uuid_str, const char *key);

/**
 * Generate a random password of `length` bytes into `buf_out`.
 *
 * The buffer receives exactly `length` bytes of password data.  If
 * `buf_len > length`, a null terminator is written at `buf_out[length]`
 * so the buffer can be used as a C string.  Callers that need a C string
 * should allocate `length + 1` bytes.
 */
enum VaultResult generate_password(uint32_t length,
                                   uint32_t charset,
                                   uint8_t *buf_out,
                                   uint32_t buf_len);

/**
 * Free a C string that was allocated by the Rust core (e.g. UUID from vault_add_entry).
 * Callers MUST use this instead of their language's native free to avoid cross-allocator UB.
 */
void string_free(char *ptr);

void entry_list_free(struct CEntryList *list);

void entry_data_free(struct CEntryData *data);

/**
 * Derive a 32-byte key from password + salt using Argon2id.
 * Parameters: 64 MB memory, 3 iterations, 2 parallelism lanes.
 * Caller must provide a 32-byte output buffer.
 */
enum VaultResult vault_derive_key_argon2(const uint8_t *password_ptr,
                                         uint32_t password_len,
                                         const uint8_t *salt_ptr,
                                         uint32_t salt_len,
                                         uint8_t *out_ptr,
                                         uint32_t out_len);

/**
 * Derive a 32-byte key from password + salt using Argon2id with high parameters.
 * Parameters: 256 MB memory, 4 iterations, 4 parallelism lanes.
 * Used for emergency and backup file encryption.
 */
enum VaultResult vault_derive_key_argon2_high(const uint8_t *password_ptr,
                                              uint32_t password_len,
                                              const uint8_t *salt_ptr,
                                              uint32_t salt_len,
                                              uint8_t *out_ptr,
                                              uint32_t out_len);

#endif  /* CITADEL_CORE_H */
